import Foundation

/// 国産ブランドの現行ラインナップ（Toyota / Lexus / Honda / Nissan）。
/// ID はブランドごとに 100 番台単位で採番する（Toyota: 100〜, Lexus: 200〜 ...）。
extension CarCatalog {

    // MARK: - Toyota (101...)

    static let toyota: [Car] = [
        Car(id: 101, maker: "Toyota", name: "GR ヤリス", body: "スポーツ", drive: "4WD",
            trans: "6MT", transType: .mt, power: 304, disp: "1.6L Turbo", fuel: "13.6",
            price: 456, colorHex: "#E53935", ev: false, tag: "ラリーホモロゲ"),
        Car(id: 102, maker: "Toyota", name: "GR カローラ", body: "スポーツ", drive: "4WD",
            trans: "6MT", transType: .mt, power: 304, disp: "1.6L Turbo", fuel: "12.0",
            price: 568, colorHex: "#D32F2F", ev: false, tag: "4WD ホットハッチ"),
        Car(id: 103, maker: "Toyota", name: "GR86", body: "クーペ", drive: "FR",
            trans: "6MT", transType: .mt, power: 235, disp: "2.4L NA", fuel: "12.0",
            price: 305, colorHex: "#D84315", ev: false, tag: "軽量 FR"),
        Car(id: 104, maker: "Toyota", name: "GR スープラ", body: "クーペ", drive: "FR",
            trans: "6MT", transType: .mt, power: 387, disp: "3.0L 直6 Turbo", fuel: "12.2",
            price: 731, colorHex: "#F4511E", ev: false, tag: "直 6 FR スポーツ"),
        Car(id: 105, maker: "Toyota", name: "プリウス", body: "セダン", drive: "FF",
            trans: "CVT", transType: .at, power: 196, disp: "2.0L HEV", fuel: "28.6",
            price: 320, colorHex: "#00897B", ev: false, tag: "ハイブリッド定番"),
        Car(id: 106, maker: "Toyota", name: "アクア", body: "コンパクト", drive: "FF",
            trans: "CVT", transType: .at, power: 116, disp: "1.5L HEV", fuel: "33.6",
            price: 215, colorHex: "#26A69A", ev: false, tag: "低燃費コンパクト"),
        Car(id: 107, maker: "Toyota", name: "ヤリス", body: "コンパクト", drive: "FF",
            trans: "CVT", transType: .at, power: 116, disp: "1.5L HEV", fuel: "36.0",
            price: 201, colorHex: "#EF5350", ev: false, tag: "世界戦略コンパクト"),
        Car(id: 108, maker: "Toyota", name: "ヤリスクロス", body: "SUV", drive: "FF",
            trans: "CVT", transType: .at, power: 116, disp: "1.5L HEV", fuel: "30.8",
            price: 240, colorHex: "#EC407A", ev: false, tag: "都会派コンパクト SUV"),
        Car(id: 109, maker: "Toyota", name: "カローラ", body: "セダン", drive: "FF",
            trans: "CVT", transType: .at, power: 140, disp: "1.8L HEV", fuel: "30.2",
            price: 218, colorHex: "#5C6BC0", ev: false, tag: "世界のカローラ"),
        Car(id: 110, maker: "Toyota", name: "カローラスポーツ", body: "コンパクト", drive: "FF",
            trans: "CVT", transType: .at, power: 140, disp: "1.8L HEV", fuel: "30.0",
            price: 226, colorHex: "#3949AB", ev: false, tag: "走りのカローラ"),
        Car(id: 111, maker: "Toyota", name: "カローラツーリング", body: "ワゴン", drive: "FF",
            trans: "CVT", transType: .at, power: 140, disp: "1.8L HEV", fuel: "29.5",
            price: 225, colorHex: "#303F9F", ev: false, tag: "使えるワゴン"),
        Car(id: 112, maker: "Toyota", name: "カローラクロス", body: "SUV", drive: "FF",
            trans: "CVT", transType: .at, power: 140, disp: "1.8L HEV", fuel: "26.4",
            price: 260, colorHex: "#7986CB", ev: false, tag: "カローラの SUV"),
        Car(id: 113, maker: "Toyota", name: "クラウンクロスオーバー", body: "SUV", drive: "AWD",
            trans: "CVT", transType: .at, power: 234, disp: "2.5L HEV", fuel: "22.4",
            price: 445, colorHex: "#263238", ev: false, tag: "新時代クラウン"),
        Car(id: 114, maker: "Toyota", name: "クラウンスポーツ", body: "SUV", drive: "AWD",
            trans: "CVT", transType: .at, power: 234, disp: "2.5L HEV", fuel: "21.3",
            price: 590, colorHex: "#37474F", ev: false, tag: "スポーティクラウン"),
        Car(id: 115, maker: "Toyota", name: "クラウンセダン", body: "セダン", drive: "FR",
            trans: "AT", transType: .at, power: 174, disp: "2.5L HEV", fuel: "18.0",
            price: 730, colorHex: "#455A64", ev: false, tag: "正統派 FR セダン"),
        Car(id: 116, maker: "Toyota", name: "クラウンエステート", body: "SUV", drive: "AWD",
            trans: "CVT", transType: .at, power: 234, disp: "2.5L HEV", fuel: "20.0",
            price: 635, colorHex: "#546E7A", ev: false, tag: "クラウンのワゴン SUV"),
        Car(id: 117, maker: "Toyota", name: "センチュリー", body: "セダン", drive: "AWD",
            trans: "AT", transType: .at, power: 412, disp: "3.5L V6 PHEV", fuel: "14.2",
            price: 2500, colorHex: "#212121", ev: false, tag: "ショーファーの頂点"),
        Car(id: 118, maker: "Toyota", name: "アルファード", body: "ミニバン", drive: "FF",
            trans: "CVT", transType: .at, power: 250, disp: "2.5L HEV", fuel: "17.7",
            price: 555, colorHex: "#4E342E", ev: false, tag: "高級ミニバンの王者"),
        Car(id: 119, maker: "Toyota", name: "ヴェルファイア", body: "ミニバン", drive: "AWD",
            trans: "AT", transType: .at, power: 279, disp: "2.4L Turbo", fuel: "10.3",
            price: 655, colorHex: "#3E2723", ev: false, tag: "威風堂々"),
        Car(id: 120, maker: "Toyota", name: "ノア", body: "ミニバン", drive: "FF",
            trans: "CVT", transType: .at, power: 184, disp: "1.8L HEV", fuel: "23.0",
            price: 305, colorHex: "#0288D1", ev: false, tag: "ファミリーの定番"),
        Car(id: 121, maker: "Toyota", name: "ヴォクシー", body: "ミニバン", drive: "FF",
            trans: "CVT", transType: .at, power: 184, disp: "1.8L HEV", fuel: "23.0",
            price: 344, colorHex: "#0277BD", ev: false, tag: "エアロミニバン"),
        Car(id: 122, maker: "Toyota", name: "シエンタ", body: "ミニバン", drive: "FF",
            trans: "CVT", transType: .at, power: 116, disp: "1.5L HEV", fuel: "28.2",
            price: 236, colorHex: "#FBC02D", ev: false, tag: "コンパクト 3 列"),
        Car(id: 123, maker: "Toyota", name: "ルーミー", body: "コンパクト", drive: "FF",
            trans: "CVT", transType: .at, power: 98, disp: "1.0L Turbo", fuel: "16.8",
            price: 175, colorHex: "#8D6E63", ev: false, tag: "背高コンパクト"),
        Car(id: 124, maker: "Toyota", name: "ライズ", body: "SUV", drive: "FF",
            trans: "CVT", transType: .at, power: 116, disp: "1.2L HEV", fuel: "28.0",
            price: 217, colorHex: "#EF6C00", ev: false, tag: "5 ナンバー SUV"),
        Car(id: 125, maker: "Toyota", name: "ハリアー", body: "SUV", drive: "FF",
            trans: "CVT", transType: .at, power: 218, disp: "2.5L HEV", fuel: "22.3",
            price: 415, colorHex: "#37474F", ev: false, tag: "都会派 SUV の元祖"),
        Car(id: 126, maker: "Toyota", name: "RAV4", body: "SUV", drive: "4WD",
            trans: "CVT", transType: .at, power: 222, disp: "2.5L HEV", fuel: "20.6",
            price: 400, colorHex: "#33691E", ev: false, tag: "タフギア SUV"),
        Car(id: 127, maker: "Toyota", name: "ランドクルーザー 300", body: "SUV", drive: "4WD",
            trans: "10AT", transType: .at, power: 415, disp: "3.5L V6 Turbo", fuel: "8.0",
            price: 800, colorHex: "#5D4037", ev: false, tag: "キング・オブ・クロカン"),
        Car(id: 128, maker: "Toyota", name: "ランドクルーザー 250", body: "SUV", drive: "4WD",
            trans: "8AT", transType: .at, power: 204, disp: "2.8L Diesel", fuel: "11.0",
            price: 520, colorHex: "#795548", ev: false, tag: "本格クロカン"),
        Car(id: 129, maker: "Toyota", name: "ランドクルーザー 70", body: "SUV", drive: "4WD",
            trans: "6AT", transType: .at, power: 204, disp: "2.8L Diesel", fuel: "10.1",
            price: 480, colorHex: "#6D4C41", ev: false, tag: "不変のヘビーデューティ"),
        Car(id: 130, maker: "Toyota", name: "ハイラックス", body: "ピックアップ", drive: "4WD",
            trans: "6AT", transType: .at, power: 204, disp: "2.4L Diesel", fuel: "11.7",
            price: 400, colorHex: "#4527A0", ev: false, tag: "国内唯一級ピックアップ"),
        Car(id: 131, maker: "Toyota", name: "bZ4X", body: "SUV", drive: "AWD",
            trans: "AT", transType: .at, power: 218, disp: "EV 71.4kWh", fuel: "航続 540km",
            price: 550, colorHex: "#00695C", ev: true, tag: "トヨタの本格 EV"),
        Car(id: 132, maker: "Toyota", name: "ミライ", body: "セダン", drive: "FR",
            trans: "AT", transType: .at, power: 182, disp: "FCEV 水素", fuel: "航続 850km",
            price: 726, colorHex: "#0097A7", ev: true, tag: "水素で走る FR"),
        Car(id: 133, maker: "Toyota", name: "ハイエース ワゴン", body: "ワゴン", drive: "FR",
            trans: "6AT", transType: .at, power: 151, disp: "2.8L Diesel", fuel: "10.2",
            price: 400, colorHex: "#616161", ev: false, tag: "働くクルマの帝王")
    ]

    // MARK: - Lexus (201...)

    static let lexus: [Car] = [
        Car(id: 201, maker: "Lexus", name: "LBX", body: "SUV", drive: "FF",
            trans: "CVT", transType: .at, power: 136, disp: "1.5L HEV", fuel: "27.7",
            price: 460, colorHex: "#607D8B", ev: false, tag: "小さな高級車"),
        Car(id: 202, maker: "Lexus", name: "UX300h", body: "SUV", drive: "FF",
            trans: "CVT", transType: .at, power: 199, disp: "2.0L HEV", fuel: "26.3",
            price: 455, colorHex: "#78909C", ev: false, tag: "アーバンコンパクト"),
        Car(id: 203, maker: "Lexus", name: "NX350h", body: "SUV", drive: "AWD",
            trans: "CVT", transType: .at, power: 243, disp: "2.5L HEV", fuel: "20.9",
            price: 520, colorHex: "#455A64", ev: false, tag: "売れ筋ミドル SUV"),
        Car(id: 204, maker: "Lexus", name: "RX500h", body: "SUV", drive: "AWD",
            trans: "6AT", transType: .at, power: 371, disp: "2.4L Turbo HEV", fuel: "14.4",
            price: 900, colorHex: "#37474F", ev: false, tag: "ラグジュアリー SUV"),
        Car(id: 205, maker: "Lexus", name: "RZ450e", body: "SUV", drive: "AWD",
            trans: "AT", transType: .at, power: 313, disp: "EV 71.4kWh", fuel: "航続 494km",
            price: 880, colorHex: "#546E7A", ev: true, tag: "レクサス初の専用 EV"),
        Car(id: 206, maker: "Lexus", name: "GX550", body: "SUV", drive: "4WD",
            trans: "10AT", transType: .at, power: 354, disp: "3.5L V6 Turbo", fuel: "8.6",
            price: 1235, colorHex: "#4E342E", ev: false, tag: "プレミアムクロカン"),
        Car(id: 207, maker: "Lexus", name: "LX600", body: "SUV", drive: "4WD",
            trans: "10AT", transType: .at, power: 415, disp: "3.5L V6 Turbo", fuel: "8.1",
            price: 1250, colorHex: "#3E2723", ev: false, tag: "レクサスの旗艦 SUV"),
        Car(id: 208, maker: "Lexus", name: "ES300h", body: "セダン", drive: "FF",
            trans: "CVT", transType: .at, power: 218, disp: "2.5L HEV", fuel: "22.3",
            price: 608, colorHex: "#5D4037", ev: false, tag: "静粛の FF セダン"),
        Car(id: 209, maker: "Lexus", name: "IS300h", body: "セダン", drive: "FR",
            trans: "CVT", transType: .at, power: 179, disp: "2.5L HEV", fuel: "18.0",
            price: 545, colorHex: "#283593", ev: false, tag: "コンパクト FR セダン"),
        Car(id: 210, maker: "Lexus", name: "IS500", body: "セダン", drive: "FR",
            trans: "8AT", transType: .at, power: 481, disp: "5.0L V8 NA", fuel: "9.4",
            price: 850, colorHex: "#1A237E", ev: false, tag: "V8 セダンの生き残り"),
        Car(id: 211, maker: "Lexus", name: "RC F", body: "クーペ", drive: "FR",
            trans: "8AT", transType: .at, power: 481, disp: "5.0L V8 NA", fuel: "8.5",
            price: 1055, colorHex: "#B71C1C", ev: false, tag: "NA V8 クーペ"),
        Car(id: 212, maker: "Lexus", name: "LC500", body: "クーペ", drive: "FR",
            trans: "10AT", transType: .at, power: 477, disp: "5.0L V8 NA", fuel: "7.8",
            price: 1500, colorHex: "#37474F", ev: false, tag: "V8 グランツーリスモ"),
        Car(id: 213, maker: "Lexus", name: "LC500 コンバーチブル", body: "オープン", drive: "FR",
            trans: "10AT", transType: .at, power: 477, disp: "5.0L V8 NA", fuel: "7.8",
            price: 1600, colorHex: "#263238", ev: false, tag: "オープン GT"),
        Car(id: 214, maker: "Lexus", name: "LS500h", body: "セダン", drive: "AWD",
            trans: "CVT", transType: .at, power: 359, disp: "3.5L V6 HEV", fuel: "12.6",
            price: 1290, colorHex: "#212121", ev: false, tag: "レクサスの旗艦セダン"),
        Car(id: 215, maker: "Lexus", name: "LM500h", body: "ミニバン", drive: "AWD",
            trans: "6AT", transType: .at, power: 371, disp: "2.4L Turbo HEV", fuel: "13.5",
            price: 2000, colorHex: "#424242", ev: false, tag: "移動するラウンジ")
    ]

    // MARK: - Honda (301...)

    static let honda: [Car] = [
        Car(id: 301, maker: "Honda", name: "シビック TYPE R", body: "スポーツ", drive: "FF",
            trans: "6MT", transType: .mt, power: 330, disp: "2.0L Turbo", fuel: "12.5",
            price: 499, colorHex: "#FF5A4D", ev: false, tag: "ホットハッチ"),
        Car(id: 302, maker: "Honda", name: "シビック", body: "コンパクト", drive: "FF",
            trans: "CVT", transType: .at, power: 182, disp: "1.5L Turbo", fuel: "16.3",
            price: 344, colorHex: "#E53935", ev: false, tag: "走りのベーシック"),
        Car(id: 303, maker: "Honda", name: "アコード", body: "セダン", drive: "FF",
            trans: "CVT", transType: .at, power: 184, disp: "2.0L e:HEV", fuel: "23.5",
            price: 545, colorHex: "#37474F", ev: false, tag: "上質 FF セダン"),
        Car(id: 304, maker: "Honda", name: "フィット", body: "コンパクト", drive: "FF",
            trans: "CVT", transType: .at, power: 123, disp: "1.5L e:HEV", fuel: "30.2",
            price: 178, colorHex: "#43A047", ev: false, tag: "低燃費コンパクト"),
        Car(id: 305, maker: "Honda", name: "ヴェゼル", body: "SUV", drive: "FF",
            trans: "CVT", transType: .at, power: 131, disp: "1.5L e:HEV", fuel: "26.0",
            price: 265, colorHex: "#00695C", ev: false, tag: "クーペ SUV"),
        Car(id: 306, maker: "Honda", name: "ZR-V", body: "SUV", drive: "AWD",
            trans: "CVT", transType: .at, power: 184, disp: "2.0L e:HEV", fuel: "21.5",
            price: 330, colorHex: "#004D40", ev: false, tag: "上質ミドル SUV"),
        Car(id: 307, maker: "Honda", name: "CR-V e:FCEV", body: "SUV", drive: "FF",
            trans: "AT", transType: .at, power: 174, disp: "FCEV + PHEV", fuel: "航続 620km",
            price: 810, colorHex: "#00838F", ev: true, tag: "水素×プラグイン"),
        Car(id: 308, maker: "Honda", name: "WR-V", body: "SUV", drive: "FF",
            trans: "CVT", transType: .at, power: 118, disp: "1.5L NA", fuel: "16.4",
            price: 210, colorHex: "#6D4C41", ev: false, tag: "コスパ SUV"),
        Car(id: 309, maker: "Honda", name: "フリード", body: "ミニバン", drive: "FF",
            trans: "CVT", transType: .at, power: 123, disp: "1.5L e:HEV", fuel: "25.4",
            price: 251, colorHex: "#0288D1", ev: false, tag: "ちょうどいいミニバン"),
        Car(id: 310, maker: "Honda", name: "ステップワゴン", body: "ミニバン", drive: "FF",
            trans: "CVT", transType: .at, power: 184, disp: "2.0L e:HEV", fuel: "20.0",
            price: 338, colorHex: "#01579B", ev: false, tag: "箱のミニバン"),
        Car(id: 311, maker: "Honda", name: "N-BOX", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 58, disp: "660cc NA", fuel: "21.6",
            price: 164, colorHex: "#8D6E63", ev: false, tag: "軽の王様"),
        Car(id: 312, maker: "Honda", name: "N-ONE", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 64, disp: "660cc Turbo", fuel: "21.8",
            price: 173, colorHex: "#5D4037", ev: false, tag: "普遍のデザイン"),
        Car(id: 313, maker: "Honda", name: "N-WGN", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 58, disp: "660cc NA", fuel: "23.2",
            price: 132, colorHex: "#795548", ev: false, tag: "実直な軽ワゴン"),
        Car(id: 314, maker: "Honda", name: "N-VAN e:", body: "軽", drive: "FF",
            trans: "AT", transType: .at, power: 64, disp: "EV 29.6kWh", fuel: "航続 245km",
            price: 244, colorHex: "#00897B", ev: true, tag: "働く軽 EV"),
        Car(id: 315, maker: "Honda", name: "プレリュード", body: "クーペ", drive: "FF",
            trans: "CVT", transType: .at, power: 184, disp: "2.0L e:HEV", fuel: "22.0",
            price: 618, colorHex: "#3F51B5", ev: false, tag: "スペシャリティ復活")
    ]

    // MARK: - Nissan (401...)

    static let nissan: [Car] = [
        Car(id: 401, maker: "Nissan", name: "フェアレディZ", body: "クーペ", drive: "FR",
            trans: "6MT", transType: .mt, power: 405, disp: "3.0L V6 Turbo", fuel: "9.5",
            price: 549, colorHex: "#F2B705", ev: false, tag: "FR ツインターボ"),
        Car(id: 402, maker: "Nissan", name: "GT-R", body: "クーペ", drive: "4WD",
            trans: "6AT", transType: .at, power: 570, disp: "3.8L V6 Turbo", fuel: "7.8",
            price: 1444, colorHex: "#37474F", ev: false, tag: "和製スーパーカー"),
        Car(id: 403, maker: "Nissan", name: "スカイライン", body: "セダン", drive: "FR",
            trans: "7AT", transType: .at, power: 405, disp: "3.0L V6 Turbo", fuel: "10.0",
            price: 558, colorHex: "#C62828", ev: false, tag: "伝統の FR セダン"),
        Car(id: 404, maker: "Nissan", name: "ノート", body: "コンパクト", drive: "FF",
            trans: "AT", transType: .at, power: 116, disp: "e-POWER 1.2L", fuel: "28.4",
            price: 230, colorHex: "#1E88E5", ev: false, tag: "電動感覚コンパクト"),
        Car(id: 405, maker: "Nissan", name: "ノート オーラ", body: "コンパクト", drive: "FF",
            trans: "AT", transType: .at, power: 136, disp: "e-POWER 1.2L", fuel: "27.2",
            price: 278, colorHex: "#1565C0", ev: false, tag: "プレミアムコンパクト"),
        Car(id: 406, maker: "Nissan", name: "リーフ", body: "SUV", drive: "FF",
            trans: "AT", transType: .at, power: 218, disp: "EV 78kWh", fuel: "航続 702km",
            price: 519, colorHex: "#00ACC1", ev: true, tag: "EV のパイオニア"),
        Car(id: 407, maker: "Nissan", name: "アリア", body: "SUV", drive: "AWD",
            trans: "AT", transType: .at, power: 394, disp: "EV 91kWh", fuel: "航続 560km",
            price: 790, colorHex: "#455A64", ev: true, tag: "電動 SUV"),
        Car(id: 408, maker: "Nissan", name: "サクラ", body: "軽", drive: "FF",
            trans: "AT", transType: .at, power: 64, disp: "EV 20kWh", fuel: "航続 180km",
            price: 260, colorHex: "#7E57C2", ev: true, tag: "軽 EV"),
        Car(id: 409, maker: "Nissan", name: "キックス", body: "SUV", drive: "FF",
            trans: "AT", transType: .at, power: 136, disp: "e-POWER 1.2L", fuel: "23.0",
            price: 300, colorHex: "#EF6C00", ev: false, tag: "コンパクト e-POWER SUV"),
        Car(id: 410, maker: "Nissan", name: "エクストレイル", body: "SUV", drive: "AWD",
            trans: "AT", transType: .at, power: 204, disp: "e-POWER 1.5L VC ターボ", fuel: "19.7",
            price: 385, colorHex: "#2E7D32", ev: false, tag: "タフ×電動 4WD"),
        Car(id: 411, maker: "Nissan", name: "セレナ", body: "ミニバン", drive: "FF",
            trans: "AT", transType: .at, power: 163, disp: "e-POWER 1.4L", fuel: "19.3",
            price: 350, colorHex: "#0277BD", ev: false, tag: "国民的ミニバン"),
        Car(id: 412, maker: "Nissan", name: "ルークス", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 64, disp: "660cc Turbo", fuel: "20.9",
            price: 185, colorHex: "#8E24AA", ev: false, tag: "スーパーハイト軽"),
        Car(id: 413, maker: "Nissan", name: "デイズ", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 52, disp: "660cc NA", fuel: "23.3",
            price: 145, colorHex: "#6A1B9A", ev: false, tag: "気軽な相棒"),
        Car(id: 414, maker: "Nissan", name: "キャラバン", body: "バン", drive: "FR",
            trans: "7AT", transType: .at, power: 132, disp: "2.4L Diesel", fuel: "12.1",
            price: 340, colorHex: "#546E7A", ev: false, tag: "プロの道具")
    ]
}
