import Foundation

/// 国産ブランドの現行ラインナップ（Mazda / Subaru / Suzuki / Daihatsu / Mitsubishi）。
extension CarCatalog {

    // MARK: - Mazda (501...)

    static let mazda: [Car] = [
        Car(id: 501, maker: "Mazda", name: "ロードスター", body: "オープン", drive: "FR",
            trans: "6MT", transType: .mt, power: 132, disp: "1.5L NA", fuel: "16.8",
            price: 289, colorHex: "#C62828", ev: false, tag: "人馬一体"),
        Car(id: 502, maker: "Mazda", name: "ロードスター RF", body: "オープン", drive: "FR",
            trans: "6MT", transType: .mt, power: 184, disp: "2.0L NA", fuel: "15.8",
            price: 393, colorHex: "#B71C1C", ev: false, tag: "電動ハードトップ"),
        Car(id: 503, maker: "Mazda", name: "MAZDA2", body: "コンパクト", drive: "FF",
            trans: "6AT", transType: .at, power: 110, disp: "1.5L NA", fuel: "20.3",
            price: 169, colorHex: "#AD1457", ev: false, tag: "上質コンパクト"),
        Car(id: 504, maker: "Mazda", name: "MAZDA3", body: "コンパクト", drive: "FF",
            trans: "6AT", transType: .at, power: 156, disp: "2.0L e-SKYACTIV G", fuel: "16.6",
            price: 251, colorHex: "#880E4F", ev: false, tag: "魂動デザイン"),
        Car(id: 505, maker: "Mazda", name: "CX-3", body: "SUV", drive: "FF",
            trans: "6AT", transType: .at, power: 116, disp: "1.8L Diesel", fuel: "23.2",
            price: 233, colorHex: "#6D4C41", ev: false, tag: "コンパクトディーゼル"),
        Car(id: 506, maker: "Mazda", name: "CX-30", body: "SUV", drive: "FF",
            trans: "6AT", transType: .at, power: 156, disp: "2.0L e-SKYACTIV G", fuel: "16.2",
            price: 264, colorHex: "#4E342E", ev: false, tag: "美しいクロスオーバー"),
        Car(id: 507, maker: "Mazda", name: "CX-5", body: "SUV", drive: "AWD",
            trans: "6AT", transType: .at, power: 200, disp: "2.2L Diesel", fuel: "17.4",
            price: 291, colorHex: "#5D4037", ev: false, tag: "ディーゼル SUV の定番"),
        Car(id: 508, maker: "Mazda", name: "CX-60", body: "SUV", drive: "AWD",
            trans: "8AT", transType: .at, power: 254, disp: "3.3L 直6 Diesel", fuel: "19.8",
            price: 470, colorHex: "#6D4C41", ev: false, tag: "直 6 ディーゼル"),
        Car(id: 509, maker: "Mazda", name: "CX-80", body: "SUV", drive: "AWD",
            trans: "8AT", transType: .at, power: 254, disp: "3.3L 直6 Diesel", fuel: "19.4",
            price: 495, colorHex: "#3E2723", ev: false, tag: "3 列プレミアム"),
        Car(id: 510, maker: "Mazda", name: "MX-30", body: "SUV", drive: "FF",
            trans: "6AT", transType: .at, power: 156, disp: "2.0L マイルド HV", fuel: "15.6",
            price: 264, colorHex: "#7B1FA2", ev: false, tag: "観音開きの個性派"),
        Car(id: 511, maker: "Mazda", name: "MX-30 Rotary-EV", body: "SUV", drive: "FF",
            trans: "AT", transType: .at, power: 170, disp: "ロータリー発電 + EV", fuel: "航続 107km(EV)",
            price: 423, colorHex: "#8E24AA", ev: true, tag: "ロータリー復活")
    ]

    // MARK: - Subaru (601...)

    static let subaru: [Car] = [
        Car(id: 601, maker: "Subaru", name: "WRX S4", body: "セダン", drive: "AWD",
            trans: "CVT", transType: .at, power: 275, disp: "2.4L Turbo", fuel: "11.0",
            price: 400, colorHex: "#1565C0", ev: false, tag: "シンメトリカル AWD"),
        Car(id: 602, maker: "Subaru", name: "BRZ", body: "クーペ", drive: "FR",
            trans: "6MT", transType: .mt, power: 235, disp: "2.4L NA", fuel: "12.0",
            price: 331, colorHex: "#0D47A1", ev: false, tag: "水平対向 FR"),
        Car(id: 603, maker: "Subaru", name: "レヴォーグ", body: "ワゴン", drive: "AWD",
            trans: "CVT", transType: .at, power: 177, disp: "1.8L Turbo", fuel: "13.6",
            price: 348, colorHex: "#1E88E5", ev: false, tag: "国産スポーツワゴン"),
        Car(id: 604, maker: "Subaru", name: "レヴォーグ レイバック", body: "ワゴン", drive: "AWD",
            trans: "CVT", transType: .at, power: 177, disp: "1.8L Turbo", fuel: "13.6",
            price: 399, colorHex: "#1976D2", ev: false, tag: "都会派クロスワゴン"),
        Car(id: 605, maker: "Subaru", name: "インプレッサ", body: "コンパクト", drive: "AWD",
            trans: "CVT", transType: .at, power: 145, disp: "2.0L e-BOXER", fuel: "16.6",
            price: 239, colorHex: "#2196F3", ev: false, tag: "安心のベーシック"),
        Car(id: 606, maker: "Subaru", name: "クロストレック", body: "SUV", drive: "AWD",
            trans: "CVT", transType: .at, power: 145, disp: "2.0L e-BOXER", fuel: "16.4",
            price: 270, colorHex: "#0288D1", ev: false, tag: "アクティブギア"),
        Car(id: 607, maker: "Subaru", name: "フォレスター", body: "SUV", drive: "AWD",
            trans: "CVT", transType: .at, power: 194, disp: "2.5L S:HEV", fuel: "19.0",
            price: 405, colorHex: "#01579B", ev: false, tag: "スバルの看板 SUV"),
        Car(id: 608, maker: "Subaru", name: "アウトバック", body: "ワゴン", drive: "AWD",
            trans: "CVT", transType: .at, power: 177, disp: "1.8L Turbo", fuel: "13.0",
            price: 429, colorHex: "#33691E", ev: false, tag: "グランドツアラー"),
        Car(id: 609, maker: "Subaru", name: "ソルテラ", body: "SUV", drive: "AWD",
            trans: "AT", transType: .at, power: 218, disp: "EV 71.4kWh", fuel: "航続 487km",
            price: 594, colorHex: "#0277BD", ev: true, tag: "スバル初の EV"),
        Car(id: 610, maker: "Subaru", name: "レックス", body: "SUV", drive: "FF",
            trans: "CVT", transType: .at, power: 87, disp: "1.2L NA", fuel: "20.7",
            price: 183, colorHex: "#26A69A", ev: false, tag: "気軽なコンパクト SUV")
    ]

    // MARK: - Suzuki (701...)

    static let suzuki: [Car] = [
        Car(id: 701, maker: "Suzuki", name: "ジムニー", body: "SUV", drive: "4WD",
            trans: "5MT", transType: .mt, power: 64, disp: "660cc Turbo", fuel: "16.2",
            price: 165, colorHex: "#2E7D32", ev: false, tag: "本格クロカン"),
        Car(id: 702, maker: "Suzuki", name: "ジムニーシエラ", body: "SUV", drive: "4WD",
            trans: "5MT", transType: .mt, power: 102, disp: "1.5L NA", fuel: "15.0",
            price: 202, colorHex: "#1B5E20", ev: false, tag: "小さな巨人"),
        Car(id: 703, maker: "Suzuki", name: "ジムニーノマド", body: "SUV", drive: "4WD",
            trans: "4AT", transType: .at, power: 102, disp: "1.5L NA", fuel: "14.3",
            price: 265, colorHex: "#33691E", ev: false, tag: "5 ドアジムニー"),
        Car(id: 704, maker: "Suzuki", name: "スイフト", body: "コンパクト", drive: "FF",
            trans: "CVT", transType: .at, power: 82, disp: "1.2L マイルド HV", fuel: "24.5",
            price: 173, colorHex: "#FBC02D", ev: false, tag: "軽快コンパクト"),
        Car(id: 705, maker: "Suzuki", name: "スイフト スポーツ", body: "スポーツ", drive: "FF",
            trans: "6MT", transType: .mt, power: 140, disp: "1.4L Turbo", fuel: "16.4",
            price: 208, colorHex: "#FDD835", ev: false, tag: "軽量ホットハッチ"),
        Car(id: 706, maker: "Suzuki", name: "フロンクス", body: "SUV", drive: "FF",
            trans: "6AT", transType: .at, power: 101, disp: "1.5L マイルド HV", fuel: "19.0",
            price: 254, colorHex: "#F57F17", ev: false, tag: "インド生まれのクーペ SUV"),
        Car(id: 707, maker: "Suzuki", name: "ソリオ", body: "ミニバン", drive: "FF",
            trans: "CVT", transType: .at, power: 91, disp: "1.2L マイルド HV", fuel: "22.3",
            price: 186, colorHex: "#0288D1", ev: false, tag: "コンパクトハイト"),
        Car(id: 708, maker: "Suzuki", name: "クロスビー", body: "SUV", drive: "FF",
            trans: "6AT", transType: .at, power: 99, disp: "1.0L Turbo", fuel: "18.2",
            price: 219, colorHex: "#F9A825", ev: false, tag: "遊べるワゴン SUV"),
        Car(id: 709, maker: "Suzuki", name: "ハスラー", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 49, disp: "660cc マイルド HV", fuel: "25.0",
            price: 152, colorHex: "#00897B", ev: false, tag: "遊べる軽"),
        Car(id: 710, maker: "Suzuki", name: "ワゴンR", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 49, disp: "660cc マイルド HV", fuel: "25.2",
            price: 132, colorHex: "#1976D2", ev: false, tag: "軽ワゴンの元祖"),
        Car(id: 711, maker: "Suzuki", name: "スペーシア", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 49, disp: "660cc マイルド HV", fuel: "23.9",
            price: 153, colorHex: "#039BE5", ev: false, tag: "スーパーハイト軽"),
        Car(id: 712, maker: "Suzuki", name: "アルト", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 46, disp: "660cc マイルド HV", fuel: "27.7",
            price: 106, colorHex: "#E53935", ev: false, tag: "原点の軽"),
        Car(id: 713, maker: "Suzuki", name: "アルト ラパン", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 49, disp: "660cc NA", fuel: "26.2",
            price: 134, colorHex: "#F48FB1", ev: false, tag: "かわいい相棒"),
        Car(id: 714, maker: "Suzuki", name: "エブリイワゴン", body: "軽", drive: "FR",
            trans: "4AT", transType: .at, power: 64, disp: "660cc Turbo", fuel: "13.4",
            price: 168, colorHex: "#546E7A", ev: false, tag: "積める軽ワゴン")
    ]

    // MARK: - Daihatsu (801...)

    static let daihatsu: [Car] = [
        Car(id: 801, maker: "Daihatsu", name: "コペン", body: "オープン", drive: "FF",
            trans: "5MT", transType: .mt, power: 64, disp: "660cc Turbo", fuel: "18.6",
            price: 193, colorHex: "#F4511E", ev: false, tag: "軽オープン"),
        Car(id: 802, maker: "Daihatsu", name: "タント", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 52, disp: "660cc NA", fuel: "22.7",
            price: 138, colorHex: "#EC407A", ev: false, tag: "ミラクルオープンドア"),
        Car(id: 803, maker: "Daihatsu", name: "ムーヴ", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 52, disp: "660cc NA", fuel: "22.6",
            price: 135, colorHex: "#AB47BC", ev: false, tag: "スライドドアで復活"),
        Car(id: 804, maker: "Daihatsu", name: "ミライース", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 49, disp: "660cc NA", fuel: "25.0",
            price: 92, colorHex: "#66BB6A", ev: false, tag: "第 3 のエコカー"),
        Car(id: 805, maker: "Daihatsu", name: "タフト", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 52, disp: "660cc NA", fuel: "20.5",
            price: 135, colorHex: "#26A69A", ev: false, tag: "スカイフィールトップ"),
        Car(id: 806, maker: "Daihatsu", name: "ロッキー", body: "SUV", drive: "FF",
            trans: "CVT", transType: .at, power: 106, disp: "1.2L e-SMART HV", fuel: "28.0",
            price: 217, colorHex: "#EF6C00", ev: false, tag: "コンパクト SUV"),
        Car(id: 807, maker: "Daihatsu", name: "トール", body: "コンパクト", drive: "FF",
            trans: "CVT", transType: .at, power: 69, disp: "1.0L NA", fuel: "18.4",
            price: 164, colorHex: "#8D6E63", ev: false, tag: "広々コンパクト"),
        Car(id: 808, maker: "Daihatsu", name: "ムーヴキャンバス", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 52, disp: "660cc NA", fuel: "22.9",
            price: 149, colorHex: "#F8BBD0", ev: false, tag: "ストライプが目印"),
        Car(id: 809, maker: "Daihatsu", name: "アトレー", body: "軽", drive: "FR",
            trans: "CVT", transType: .at, power: 64, disp: "660cc Turbo", fuel: "14.7",
            price: 156, colorHex: "#455A64", ev: false, tag: "遊べる軽バン"),
        Car(id: 810, maker: "Daihatsu", name: "ハイゼットカーゴ", body: "軽", drive: "FR",
            trans: "CVT", transType: .at, power: 53, disp: "660cc NA", fuel: "15.6",
            price: 118, colorHex: "#607D8B", ev: false, tag: "働く軽の定番")
    ]

    // MARK: - Mitsubishi (901...)

    static let mitsubishi: [Car] = [
        Car(id: 901, maker: "Mitsubishi", name: "アウトランダー PHEV", body: "SUV", drive: "4WD",
            trans: "AT", transType: .at, power: 252, disp: "2.4L PHEV", fuel: "16.2",
            price: 526, colorHex: "#B71C1C", ev: false, tag: "PHEV の先駆者"),
        Car(id: 902, maker: "Mitsubishi", name: "エクリプスクロス PHEV", body: "SUV", drive: "4WD",
            trans: "AT", transType: .at, power: 188, disp: "2.4L PHEV", fuel: "16.4",
            price: 451, colorHex: "#C62828", ev: false, tag: "クーペ SUV × PHEV"),
        Car(id: 903, maker: "Mitsubishi", name: "デリカ D:5", body: "ミニバン", drive: "4WD",
            trans: "8AT", transType: .at, power: 145, disp: "2.2L Diesel", fuel: "12.6",
            price: 419, colorHex: "#2E7D32", ev: false, tag: "オールラウンドミニバン"),
        Car(id: 904, maker: "Mitsubishi", name: "デリカミニ", body: "軽", drive: "4WD",
            trans: "CVT", transType: .at, power: 64, disp: "660cc Turbo", fuel: "17.5",
            price: 204, colorHex: "#33691E", ev: false, tag: "タフかわ軽"),
        Car(id: 905, maker: "Mitsubishi", name: "eK クロス", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 64, disp: "660cc Turbo", fuel: "21.5",
            price: 160, colorHex: "#5D4037", ev: false, tag: "SUV テイスト軽"),
        Car(id: 906, maker: "Mitsubishi", name: "eK クロス EV", body: "軽", drive: "FF",
            trans: "AT", transType: .at, power: 64, disp: "EV 20kWh", fuel: "航続 180km",
            price: 257, colorHex: "#00695C", ev: true, tag: "軽 EV クロスオーバー"),
        Car(id: 907, maker: "Mitsubishi", name: "eK ワゴン", body: "軽", drive: "FF",
            trans: "CVT", transType: .at, power: 52, disp: "660cc NA", fuel: "23.2",
            price: 139, colorHex: "#6D4C41", ev: false, tag: "堅実な軽ワゴン"),
        Car(id: 908, maker: "Mitsubishi", name: "トライトン", body: "ピックアップ", drive: "4WD",
            trans: "6AT", transType: .at, power: 204, disp: "2.4L Diesel", fuel: "11.3",
            price: 498, colorHex: "#37474F", ev: false, tag: "ピックアップ復活")
    ]
}
