import Foundation

/// ドイツブランドの現行ラインナップ（Mercedes-Benz / BMW / Audi / Volkswagen / Porsche）。
extension CarCatalog {

    // MARK: - Mercedes-Benz (1001...)

    static let mercedesBenz: [Car] = [
        Car(id: 1001, maker: "Mercedes-Benz", name: "A クラス", body: "コンパクト", drive: "FF",
            trans: "7AT", transType: .at, power: 136, disp: "1.3L Turbo", fuel: "16.6",
            price: 508, colorHex: "#455A64", ev: false, tag: "入門メルセデス"),
        Car(id: 1002, maker: "Mercedes-Benz", name: "CLA", body: "セダン", drive: "FF",
            trans: "7AT", transType: .at, power: 150, disp: "2.0L Diesel", fuel: "19.7",
            price: 599, colorHex: "#546E7A", ev: false, tag: "4 ドアクーペ"),
        Car(id: 1003, maker: "Mercedes-Benz", name: "C クラス", body: "セダン", drive: "FR",
            trans: "9AT", transType: .at, power: 204, disp: "2.0L Turbo MHEV", fuel: "14.9",
            price: 699, colorHex: "#37474F", ev: false, tag: "小さな S クラス"),
        Car(id: 1004, maker: "Mercedes-Benz", name: "E クラス", body: "セダン", drive: "FR",
            trans: "9AT", transType: .at, power: 204, disp: "2.0L Turbo MHEV", fuel: "13.9",
            price: 998, colorHex: "#263238", ev: false, tag: "ビジネスセダンの規範"),
        Car(id: 1005, maker: "Mercedes-Benz", name: "S クラス", body: "セダン", drive: "AWD",
            trans: "9AT", transType: .at, power: 435, disp: "3.0L 直6 Turbo MHEV", fuel: "11.2",
            price: 1722, colorHex: "#212121", ev: false, tag: "世界のベンチマーク"),
        Car(id: 1006, maker: "Mercedes-Benz", name: "マイバッハ S クラス", body: "セダン", drive: "AWD",
            trans: "9AT", transType: .at, power: 612, disp: "6.0L V12 Turbo", fuel: "7.5",
            price: 3300, colorHex: "#1A1A1A", ev: false, tag: "究極のショーファー"),
        Car(id: 1007, maker: "Mercedes-Benz", name: "AMG GT", body: "クーペ", drive: "AWD",
            trans: "9AT", transType: .at, power: 585, disp: "4.0L V8 Turbo", fuel: "7.5",
            price: 2900, colorHex: "#B71C1C", ev: false, tag: "AMG の旗艦クーペ"),
        Car(id: 1008, maker: "Mercedes-Benz", name: "SL", body: "オープン", drive: "AWD",
            trans: "9AT", transType: .at, power: 585, disp: "4.0L V8 Turbo", fuel: "7.8",
            price: 3060, colorHex: "#880E4F", ev: false, tag: "伝統のロードスター"),
        Car(id: 1009, maker: "Mercedes-Benz", name: "GLA", body: "SUV", drive: "FF",
            trans: "8AT", transType: .at, power: 150, disp: "2.0L Diesel", fuel: "17.9",
            price: 649, colorHex: "#607D8B", ev: false, tag: "コンパクト SUV"),
        Car(id: 1010, maker: "Mercedes-Benz", name: "GLB", body: "SUV", drive: "FF",
            trans: "8AT", transType: .at, power: 150, disp: "2.0L Diesel", fuel: "16.5",
            price: 690, colorHex: "#78909C", ev: false, tag: "スクエアな 7 人乗り"),
        Car(id: 1011, maker: "Mercedes-Benz", name: "GLC", body: "SUV", drive: "AWD",
            trans: "9AT", transType: .at, power: 204, disp: "2.0L Turbo MHEV", fuel: "13.5",
            price: 848, colorHex: "#455A64", ev: false, tag: "世界で一番売れるベンツ"),
        Car(id: 1012, maker: "Mercedes-Benz", name: "GLE", body: "SUV", drive: "AWD",
            trans: "9AT", transType: .at, power: 330, disp: "3.0L 直6 Diesel", fuel: "12.0",
            price: 1290, colorHex: "#37474F", ev: false, tag: "ラグジュアリー SUV"),
        Car(id: 1013, maker: "Mercedes-Benz", name: "GLS", body: "SUV", drive: "AWD",
            trans: "9AT", transType: .at, power: 330, disp: "3.0L 直6 Diesel", fuel: "10.5",
            price: 1550, colorHex: "#263238", ev: false, tag: "SUV の S クラス"),
        Car(id: 1014, maker: "Mercedes-Benz", name: "G クラス", body: "SUV", drive: "4WD",
            trans: "9AT", transType: .at, power: 330, disp: "3.0L 直6 Diesel", fuel: "9.0",
            price: 1580, colorHex: "#33691E", ev: false, tag: "不動のゲレンデ"),
        Car(id: 1015, maker: "Mercedes-Benz", name: "EQA", body: "SUV", drive: "FF",
            trans: "AT", transType: .at, power: 190, disp: "EV 66.5kWh", fuel: "航続 555km",
            price: 782, colorHex: "#00695C", ev: true, tag: "入門電動 SUV"),
        Car(id: 1016, maker: "Mercedes-Benz", name: "EQB", body: "SUV", drive: "FF",
            trans: "AT", transType: .at, power: 190, disp: "EV 66.5kWh", fuel: "航続 520km",
            price: 822, colorHex: "#00796B", ev: true, tag: "電動 7 シーター"),
        Car(id: 1017, maker: "Mercedes-Benz", name: "EQE", body: "セダン", drive: "FR",
            trans: "AT", transType: .at, power: 292, disp: "EV 90.6kWh", fuel: "航続 624km",
            price: 1262, colorHex: "#004D40", ev: true, tag: "電動ビジネスセダン"),
        Car(id: 1018, maker: "Mercedes-Benz", name: "EQS", body: "セダン", drive: "FR",
            trans: "AT", transType: .at, power: 360, disp: "EV 107.8kWh", fuel: "航続 700km",
            price: 1578, colorHex: "#1B5E20", ev: true, tag: "電動フラッグシップ")
    ]

    // MARK: - BMW (1101...)

    static let bmw: [Car] = [
        Car(id: 1101, maker: "BMW", name: "1シリーズ", body: "コンパクト", drive: "FF",
            trans: "7AT", transType: .at, power: 170, disp: "1.5L Turbo MHEV", fuel: "15.6",
            price: 498, colorHex: "#1565C0", ev: false, tag: "駆けぬける入門"),
        Car(id: 1102, maker: "BMW", name: "2シリーズ グランクーペ", body: "セダン", drive: "FF",
            trans: "7AT", transType: .at, power: 170, disp: "1.5L Turbo MHEV", fuel: "15.0",
            price: 545, colorHex: "#0D47A1", ev: false, tag: "小さな 4 ドアクーペ"),
        Car(id: 1103, maker: "BMW", name: "3シリーズ", body: "セダン", drive: "FR",
            trans: "8AT", transType: .at, power: 184, disp: "2.0L Turbo", fuel: "13.6",
            price: 632, colorHex: "#1976D2", ev: false, tag: "スポーツセダンの基準"),
        Car(id: 1104, maker: "BMW", name: "4シリーズ クーペ", body: "クーペ", drive: "FR",
            trans: "8AT", transType: .at, power: 184, disp: "2.0L Turbo", fuel: "13.2",
            price: 678, colorHex: "#283593", ev: false, tag: "エレガント FR クーペ"),
        Car(id: 1105, maker: "BMW", name: "5シリーズ", body: "セダン", drive: "FR",
            trans: "8AT", transType: .at, power: 190, disp: "2.0L Turbo MHEV", fuel: "13.0",
            price: 848, colorHex: "#303F9F", ev: false, tag: "8 世代目の風格"),
        Car(id: 1106, maker: "BMW", name: "7シリーズ", body: "セダン", drive: "FR",
            trans: "8AT", transType: .at, power: 381, disp: "3.0L 直6 Turbo MHEV", fuel: "11.0",
            price: 1748, colorHex: "#1A237E", ev: false, tag: "BMW の旗艦"),
        Car(id: 1107, maker: "BMW", name: "8シリーズ クーペ", body: "クーペ", drive: "FR",
            trans: "8AT", transType: .at, power: 340, disp: "3.0L 直6 Turbo", fuel: "10.5",
            price: 1459, colorHex: "#0D47A1", ev: false, tag: "ラグジュアリー GT"),
        Car(id: 1108, maker: "BMW", name: "X1", body: "SUV", drive: "FF",
            trans: "7AT", transType: .at, power: 136, disp: "1.5L Turbo MHEV", fuel: "14.3",
            price: 568, colorHex: "#0277BD", ev: false, tag: "コンパクト SAV"),
        Car(id: 1109, maker: "BMW", name: "X2", body: "SUV", drive: "FF",
            trans: "7AT", transType: .at, power: 170, disp: "1.5L Turbo MHEV", fuel: "13.8",
            price: 598, colorHex: "#01579B", ev: false, tag: "クーペ SAV"),
        Car(id: 1110, maker: "BMW", name: "X3", body: "SUV", drive: "AWD",
            trans: "8AT", transType: .at, power: 208, disp: "2.0L Turbo MHEV", fuel: "12.7",
            price: 798, colorHex: "#039BE5", ev: false, tag: "ミドル SAV の定番"),
        Car(id: 1111, maker: "BMW", name: "X5", body: "SUV", drive: "AWD",
            trans: "8AT", transType: .at, power: 352, disp: "3.0L 直6 Diesel MHEV", fuel: "12.4",
            price: 1298, colorHex: "#0288D1", ev: false, tag: "SAV の元祖"),
        Car(id: 1112, maker: "BMW", name: "X6", body: "SUV", drive: "AWD",
            trans: "8AT", transType: .at, power: 381, disp: "3.0L 直6 Turbo MHEV", fuel: "10.2",
            price: 1428, colorHex: "#0277BD", ev: false, tag: "クーペ SUV の先駆け"),
        Car(id: 1113, maker: "BMW", name: "X7", body: "SUV", drive: "AWD",
            trans: "8AT", transType: .at, power: 381, disp: "3.0L 直6 Turbo MHEV", fuel: "9.7",
            price: 1595, colorHex: "#01579B", ev: false, tag: "7 人乗りの旗艦 SAV"),
        Car(id: 1114, maker: "BMW", name: "XM", body: "SUV", drive: "AWD",
            trans: "8AT", transType: .at, power: 653, disp: "4.4L V8 PHEV", fuel: "10.1",
            price: 2318, colorHex: "#B71C1C", ev: false, tag: "M 専用 PHEV SUV"),
        Car(id: 1115, maker: "BMW", name: "Z4", body: "オープン", drive: "FR",
            trans: "8AT", transType: .at, power: 197, disp: "2.0L Turbo", fuel: "12.9",
            price: 668, colorHex: "#E53935", ev: false, tag: "ピュアロードスター"),
        Car(id: 1116, maker: "BMW", name: "M2", body: "クーペ", drive: "FR",
            trans: "6MT", transType: .mt, power: 480, disp: "3.0L 直6 Turbo", fuel: "9.7",
            price: 998, colorHex: "#00695C", ev: false, tag: "MT で乗れる M"),
        Car(id: 1117, maker: "BMW", name: "M3", body: "セダン", drive: "FR",
            trans: "6MT", transType: .mt, power: 480, disp: "3.0L 直6 Turbo", fuel: "9.4",
            price: 1198, colorHex: "#004D40", ev: false, tag: "M の代名詞"),
        Car(id: 1118, maker: "BMW", name: "M4 クーペ", body: "クーペ", drive: "AWD",
            trans: "8AT", transType: .at, power: 530, disp: "3.0L 直6 Turbo", fuel: "9.0",
            price: 1348, colorHex: "#00838F", ev: false, tag: "サーキット直系"),
        Car(id: 1119, maker: "BMW", name: "i4", body: "セダン", drive: "FR",
            trans: "AT", transType: .at, power: 340, disp: "EV 83.9kWh", fuel: "航続 604km",
            price: 848, colorHex: "#00ACC1", ev: true, tag: "電動グランクーペ"),
        Car(id: 1120, maker: "BMW", name: "i5", body: "セダン", drive: "FR",
            trans: "AT", transType: .at, power: 340, disp: "EV 81.2kWh", fuel: "航続 571km",
            price: 998, colorHex: "#0097A7", ev: true, tag: "電動 5 シリーズ"),
        Car(id: 1121, maker: "BMW", name: "i7", body: "セダン", drive: "AWD",
            trans: "AT", transType: .at, power: 544, disp: "EV 101.7kWh", fuel: "航続 650km",
            price: 2198, colorHex: "#006064", ev: true, tag: "電動旗艦サルーン"),
        Car(id: 1122, maker: "BMW", name: "iX", body: "SUV", drive: "AWD",
            trans: "AT", transType: .at, power: 523, disp: "EV 111.5kWh", fuel: "航続 650km",
            price: 1548, colorHex: "#00838F", ev: true, tag: "電動フラッグシップ SAV")
    ]

    // MARK: - Audi (1201...)

    static let audi: [Car] = [
        Car(id: 1201, maker: "Audi", name: "A1 スポーツバック", body: "コンパクト", drive: "FF",
            trans: "7AT", transType: .at, power: 116, disp: "1.0L Turbo", fuel: "17.0",
            price: 399, colorHex: "#757575", ev: false, tag: "プレミアム入門"),
        Car(id: 1202, maker: "Audi", name: "A3 スポーツバック", body: "コンパクト", drive: "FF",
            trans: "7AT", transType: .at, power: 150, disp: "1.5L Turbo MHEV", fuel: "15.9",
            price: 480, colorHex: "#616161", ev: false, tag: "端正なハッチ"),
        Car(id: 1203, maker: "Audi", name: "A5", body: "セダン", drive: "FF",
            trans: "7AT", transType: .at, power: 204, disp: "2.0L Turbo MHEV", fuel: "13.5",
            price: 700, colorHex: "#546E7A", ev: false, tag: "A4 後継の新世代"),
        Car(id: 1204, maker: "Audi", name: "A6", body: "セダン", drive: "AWD",
            trans: "7AT", transType: .at, power: 265, disp: "2.0L Turbo MHEV", fuel: "12.0",
            price: 880, colorHex: "#455A64", ev: false, tag: "クワトロの風格"),
        Car(id: 1205, maker: "Audi", name: "A7 スポーツバック", body: "セダン", drive: "AWD",
            trans: "7AT", transType: .at, power: 340, disp: "3.0L V6 Turbo MHEV", fuel: "10.8",
            price: 1230, colorHex: "#37474F", ev: false, tag: "流麗な 5 ドアクーペ"),
        Car(id: 1206, maker: "Audi", name: "A8", body: "セダン", drive: "AWD",
            trans: "8AT", transType: .at, power: 340, disp: "3.0L V6 Turbo MHEV", fuel: "10.6",
            price: 1420, colorHex: "#263238", ev: false, tag: "テクノロジー旗艦"),
        Car(id: 1207, maker: "Audi", name: "Q2", body: "SUV", drive: "FF",
            trans: "7AT", transType: .at, power: 150, disp: "1.5L Turbo", fuel: "14.9",
            price: 460, colorHex: "#78909C", ev: false, tag: "小さなクワトロ魂"),
        Car(id: 1208, maker: "Audi", name: "Q3", body: "SUV", drive: "AWD",
            trans: "7AT", transType: .at, power: 150, disp: "1.5L Turbo", fuel: "14.0",
            price: 555, colorHex: "#607D8B", ev: false, tag: "使えるコンパクト SUV"),
        Car(id: 1209, maker: "Audi", name: "Q4 e-tron", body: "SUV", drive: "RWD",
            trans: "AT", transType: .at, power: 286, disp: "EV 82kWh", fuel: "航続 594km",
            price: 700, colorHex: "#00695C", ev: true, tag: "電動クワトロ入門"),
        Car(id: 1210, maker: "Audi", name: "Q5", body: "SUV", drive: "AWD",
            trans: "7AT", transType: .at, power: 204, disp: "2.0L Turbo MHEV", fuel: "12.6",
            price: 780, colorHex: "#455A64", ev: false, tag: "世界の売れ筋"),
        Car(id: 1211, maker: "Audi", name: "Q7", body: "SUV", drive: "AWD",
            trans: "8AT", transType: .at, power: 340, disp: "3.0L V6 Turbo MHEV", fuel: "9.7",
            price: 1130, colorHex: "#37474F", ev: false, tag: "7 人乗り上級 SUV"),
        Car(id: 1212, maker: "Audi", name: "Q8", body: "SUV", drive: "AWD",
            trans: "8AT", transType: .at, power: 340, disp: "3.0L V6 Turbo MHEV", fuel: "9.3",
            price: 1250, colorHex: "#263238", ev: false, tag: "SUV クーペの旗艦"),
        Car(id: 1213, maker: "Audi", name: "RS3 スポーツバック", body: "スポーツ", drive: "AWD",
            trans: "7AT", transType: .at, power: 400, disp: "2.5L 直5 Turbo", fuel: "10.4",
            price: 990, colorHex: "#B71C1C", ev: false, tag: "5 気筒サウンド"),
        Car(id: 1214, maker: "Audi", name: "RS6 アバント", body: "ワゴン", drive: "AWD",
            trans: "8AT", transType: .at, power: 600, disp: "4.0L V8 Turbo MHEV", fuel: "8.0",
            price: 1970, colorHex: "#880E4F", ev: false, tag: "最速ワゴン"),
        Car(id: 1215, maker: "Audi", name: "e-tron GT", body: "クーペ", drive: "AWD",
            trans: "AT", transType: .at, power: 680, disp: "EV 105kWh", fuel: "航続 609km",
            price: 1876, colorHex: "#004D40", ev: true, tag: "電動グランツーリスモ")
    ]

    // MARK: - Volkswagen (1301...)

    static let volkswagen: [Car] = [
        Car(id: 1301, maker: "Volkswagen", name: "ポロ", body: "コンパクト", drive: "FF",
            trans: "7AT", transType: .at, power: 95, disp: "1.0L Turbo", fuel: "17.1",
            price: 320, colorHex: "#0D47A1", ev: false, tag: "質実剛健コンパクト"),
        Car(id: 1302, maker: "Volkswagen", name: "ゴルフ", body: "コンパクト", drive: "FF",
            trans: "7AT", transType: .at, power: 150, disp: "1.5L Turbo MHEV", fuel: "17.3",
            price: 390, colorHex: "#1565C0", ev: false, tag: "ハッチバックの世界基準"),
        Car(id: 1303, maker: "Volkswagen", name: "ゴルフ GTI", body: "スポーツ", drive: "FF",
            trans: "7AT", transType: .at, power: 265, disp: "2.0L Turbo", fuel: "13.5",
            price: 559, colorHex: "#C62828", ev: false, tag: "ホットハッチの原点"),
        Car(id: 1304, maker: "Volkswagen", name: "ゴルフ R", body: "スポーツ", drive: "4WD",
            trans: "7AT", transType: .at, power: 333, disp: "2.0L Turbo", fuel: "11.7",
            price: 679, colorHex: "#1A237E", ev: false, tag: "オールラウンド最速"),
        Car(id: 1305, maker: "Volkswagen", name: "ゴルフ ヴァリアント", body: "ワゴン", drive: "FF",
            trans: "7AT", transType: .at, power: 150, disp: "1.5L Turbo MHEV", fuel: "17.0",
            price: 419, colorHex: "#283593", ev: false, tag: "実用ワゴン"),
        Car(id: 1306, maker: "Volkswagen", name: "T-クロス", body: "SUV", drive: "FF",
            trans: "7AT", transType: .at, power: 116, disp: "1.0L Turbo", fuel: "16.9",
            price: 339, colorHex: "#EF6C00", ev: false, tag: "気軽なコンパクト SUV"),
        Car(id: 1307, maker: "Volkswagen", name: "T-ロック", body: "SUV", drive: "FF",
            trans: "7AT", transType: .at, power: 150, disp: "1.5L Turbo", fuel: "15.9",
            price: 419, colorHex: "#F57C00", ev: false, tag: "デザイン系 SUV"),
        Car(id: 1308, maker: "Volkswagen", name: "ティグアン", body: "SUV", drive: "FF",
            trans: "7AT", transType: .at, power: 150, disp: "1.5L Turbo MHEV", fuel: "15.4",
            price: 549, colorHex: "#455A64", ev: false, tag: "欧州売れ筋 SUV"),
        Car(id: 1309, maker: "Volkswagen", name: "パサート ヴァリアント", body: "ワゴン", drive: "FF",
            trans: "7AT", transType: .at, power: 150, disp: "1.5L Turbo MHEV", fuel: "16.0",
            price: 599, colorHex: "#37474F", ev: false, tag: "堂々のミドルワゴン"),
        Car(id: 1310, maker: "Volkswagen", name: "ID.4", body: "SUV", drive: "RWD",
            trans: "AT", transType: .at, power: 204, disp: "EV 77kWh", fuel: "航続 618km",
            price: 649, colorHex: "#00695C", ev: true, tag: "VW 電動の主力"),
        Car(id: 1311, maker: "Volkswagen", name: "ID. Buzz", body: "ミニバン", drive: "RWD",
            trans: "AT", transType: .at, power: 286, disp: "EV 86kWh", fuel: "航続 524km",
            price: 899, colorHex: "#F9A825", ev: true, tag: "ワーゲンバス再来")
    ]

    // MARK: - Porsche (1401...)

    static let porsche: [Car] = [
        Car(id: 1401, maker: "Porsche", name: "911 カレラ", body: "クーペ", drive: "RR",
            trans: "8AT", transType: .at, power: 394, disp: "3.0L 水平6 Turbo", fuel: "10.5",
            price: 1690, colorHex: "#B71C1C", ev: false, tag: "スポーツカーの定義"),
        Car(id: 1402, maker: "Porsche", name: "911 GT3", body: "クーペ", drive: "RR",
            trans: "6MT", transType: .mt, power: 510, disp: "4.0L 水平6 NA", fuel: "8.0",
            price: 2900, colorHex: "#C62828", ev: false, tag: "9000rpm の NA"),
        Car(id: 1403, maker: "Porsche", name: "718 ケイマン", body: "クーペ", drive: "MR",
            trans: "6MT", transType: .mt, power: 300, disp: "2.0L 水平4 Turbo", fuel: "11.2",
            price: 942, colorHex: "#F9A825", ev: false, tag: "ミッドシップの教科書"),
        Car(id: 1404, maker: "Porsche", name: "718 ボクスター", body: "オープン", drive: "MR",
            trans: "6MT", transType: .mt, power: 300, disp: "2.0L 水平4 Turbo", fuel: "11.0",
            price: 964, colorHex: "#F57F17", ev: false, tag: "オープンミッドシップ"),
        Car(id: 1405, maker: "Porsche", name: "タイカン", body: "セダン", drive: "AWD",
            trans: "AT", transType: .at, power: 408, disp: "EV 105kWh", fuel: "航続 678km",
            price: 1481, colorHex: "#004D40", ev: true, tag: "電動ポルシェ"),
        Car(id: 1406, maker: "Porsche", name: "パナメーラ", body: "セダン", drive: "AWD",
            trans: "8AT", transType: .at, power: 353, disp: "2.9L V6 Turbo", fuel: "10.0",
            price: 1642, colorHex: "#37474F", ev: false, tag: "4 ドアスポーツ"),
        Car(id: 1407, maker: "Porsche", name: "マカン", body: "SUV", drive: "AWD",
            trans: "AT", transType: .at, power: 408, disp: "EV 100kWh", fuel: "航続 613km",
            price: 1105, colorHex: "#00695C", ev: true, tag: "電動化したベストセラー"),
        Car(id: 1408, maker: "Porsche", name: "カイエン", body: "SUV", drive: "AWD",
            trans: "8AT", transType: .at, power: 353, disp: "3.0L V6 Turbo", fuel: "8.9",
            price: 1400, colorHex: "#455A64", ev: false, tag: "スポーツ SUV の開祖")
    ]
}
